### ISSUE TITLE
Compact or Expanded Header?

### ISSUE THREAD

**Issue by horsburgh** [CZOData/YODA-File#1]
**My original question**:  Are we keeping the expanded header format or the compact header format?

**Anthony's response**:  I think we want to allow both the expanded and compact header formats. The Expanded is much easier to read for simple files. But the Compact is much more... compact... and therefore easier to scroll through for complex files.  Also, the compact form is much easier for us to deploy using the excel templates, so we will only output the compact form from Excel templates unless there is a compelling reason to reconsider. Does this make sense?

**Comment by horsburgh** [comment]
It's potentially OK to support both expanded and compact formats. However, I want to reserve final judgement until I talk to Stephanie and Jacob about how they are parsing using the ODM2 API.  The general purpose PyYAML parser doesn't care, but it might be more work to massage both into the ODM2 API object structures.  I'll chat with them.

**Comment by SRGDamia1** [comment]
The Excel template is currently using the compact form for all fields but the dataset and the citation.  I'll change those two field to compact.

**Comment by horsburgh** [comment]
Thanks Sara. I'm not sure why I left those two blocks in expanded format in my examples, but I have since fixed them.  We also had to make some relatively minor changes over the past few days because I hadn't referenced the authors correctly and there were some items in the files that were not named the same as they are named in ODM2.  These should all be done in my iUTAH examples now.

**Comment by horsburgh** [comment]
The new time series template uses compact header format.  Closing.
