### ISSUE TITLE
Enclose Text in Quotations?

### ISSUE THREAD

**Issue by horsburgh** [CZOData/YODA-File#10]
How much of the text in the YODA files do we want to enclose in quotation marks?  It matters for things like dates and URLs (which may contain YAML special characters).

**Comment by SRGDamia1** [comment]
Does it matter for the parsing?  In my excel template I'm just enclosing _all_ text in quotes just to be safe.  That way if someone has a description or code with special characters, they don't have to be dealt with in any weird way or screw up the YAML the excel produces.  It's also just easier for me to put everything in quotes than to think hard about which fields are likely to need it and which aren't.

**Comment by horsburgh** [comment]
I think Sara's implementation is OK for now.  Closing.
