### ISSUE TITLE
Non-Sequential Anchors

### ISSUE THREAD

**Issue by SRGDamia1** [CZOData/YODA-File#13]
Does it matter for the parsing if I skip numbers when creating the various anchors?  The anchors will be in order and come before any call on that anchor, but not every number will be represented.

**Comment by horsburgh** [comment]
I don't think so as long as you maintain the link from any references to the right anchor.  Stephanie and Jacob can chime in if needed.

**Comment by SRGDamia1** [comment]
Ok.  Good.  That makes things much easier in Excel.
