### ISSUE TITLE
Correction in Excel Macros 

### ISSUE THREAD

**Issue by jmeline** [CZOData/YODA-File#14]
When generating a Yoda file from the Excel Macros, the field Dataset needs to be adjusted. @horsburgh suggested that we change the fields names to be respectively Dataset.

```
Datasets:
  - &DataSetID0001 {DataSetUUID:  NULL,  DataSetTypeCV:  "Multi-time series",  DataSetCode:  "TWDEF_AirTemp",  DataSetTitle:  "Air temperature at the TW Daniels Experimental Forest Climate Station",  DataSetAbstract:  "Air temperature at the TW Daniels Experimental Forest Climate Station. The data were measured using a Campbell Scientific HC2S3 temperature and relative humidity sensor. Measurements represent the average over the 15 minute recording period."} 
```

**Comment by horsburgh** [comment]
I _think_ I have finally gotten rid of all of the upper case "S" characters in Datasets within the ODM2 DBWrench schema and the scripts for generating blank ODM2 databases.  We were inconsistent in our use.  Since "dataset" is one word, it will appear in ODM2 as "Dataset".

**Comment by SRGDamia1** [comment]
Fixed.

**Comment by jmeline** [comment]
In the generated YAML file, there are two more locations that need to be fixed.

```
DataSetCitations:
  - {DataSetObj: *DataSetID0001, CitationObj: *CitationID0001, RelationshipTypeCV: IsAllOf}
```

```
DataSetsResults:
  - {DataSetObj: *DataSetID0001, ResultObj: *ResultID0001}
  - {DataSetObj: *DataSetID0001, ResultObj: *ResultID0002}
  - {DataSetObj: *DataSetID0001, ResultObj: *ResultID0003}
```

In the SQL, these have been changed by the recent changes in the database but haven't been changed in the generated YAML files.

Also, I am not sure where this needs to go, but 'SamplingFeaturesExternalIdentifiers' in the YAML file doesn't exist in the database schema, it is 'SamplingFeatureExternalIdentifiers'

**Comment by SRGDamia1** [comment]
Fixed in today's commit.
