### ISSUE TITLE
Issues with loading Timeseries_Template_Working.yaml 

### ISSUE THREAD

**Issue by jmeline** [CZOData/YODA-File#17]
I have been working with the Timeseries_Template_Working.yaml file and noticed a few errors that need to be addressed. These are the errors that I have run into so far. 

(Each category heading is the heading for the table in YAML)
# Affiliations
- [x] AffiliationStartDate cannot be NULL
# SpatialOffset
- [x] Spatialoffset is mispelled, it needs to be SpatialOffset
- [x] Offset1UnitObj:  "meters" is incorrect. Anything that ends with Obj needs to be a reference to an object.
# Actions
- [x] BeginDateTime cannot be NULL
# Variables
- [x] SpeciationCV cannot be  NULL and must be an accepted CV_Term
# Datasets
- [x] DatasetUUID cannot be NULL. 

This is also apparent in the Specimen_Template_Working.yaml.

**Comment by SRGDamia1** [comment]
I don't want to force users of the template to put in an association start date, so we either need to make the field null-able or come up with a default value for it.

Fixed the spatial offset capitalization.

Units.. yes.. it's a problem.  The UnitTypeCV and the default units are still in progress.  Until they're settled, this won't be.

Sometimes the timing of an action is unknown, so if we can't make that field null, we need a default value for it.

And SpeciationCV is null-able...  Why do you think it isn't?  Though, actually I'm not using the CV correctly for it right now, so if it's not null, people could put something wrong in there.  I'll fix that.

**Comment by SRGDamia1** [comment]
Fixed the Variables worksheet to only allow users to select Speciation terms from the CV.   But it's still allowed to be null.

**Comment by jmeline** [comment]
@SRGDamia1 I apologize. The SpeciationCV can be null. My bad on that one! Thanks for the hard work and the nice excel macros script.

**Comment by SRGDamia1** [comment]
It's good that you pointed out the SpeciationCV though, because when I looked into that one I found I wasn't using the correct CV terms.

**Comment by horsburgh** [comment]
I believe these have been addressed.
