### ISSUE TITLE
Switched CV's from "name" to "term"

### ISSUE THREAD

**Issue by SRGDamia1** [CZOData/YODA-File#21]
I switched over the implementation of all of the controlled vocabularies in the templates to require a controlled term instead of the term's name.  Will this make problems with parsing?  @jmeline will this cause problems for you?

**Comment by horsburgh** [comment]
Any user displays (including the drop down lists in the Excel Templates) of the CV "terms" need to use the human readable "name" and not the URI friendly "term".

**Comment by SRGDamia1** [comment]
Ok, I'll switch it back.  Will the name _always_ be the second column of every downloadable csv?  I pulled the term because I assumed it would always be the first column.

**Comment by horsburgh** [comment]
Are you using the SKOS or the CSV?  Either way it would be best to reference the element/column by name and not by an index/column number.  It's probably safe to assume the format won't change because it is coded in, but, just in case...

**Comment by SRGDamia1** [comment]
I'm using the csv; it's much easier for me to import into excel.  I can work on the code to find the reference by name, but it was much faster and easier to just pull the column number.

**Comment by emiliom** [comment]
I also agree that you should reference by column name rather than number/index.

**Comment by SRGDamia1** [comment]
Fixed to pull the name instead of the term and to search csv for the column titled "name."  Upped the version to 0.2.1-alpha.  Note that the new code is dependent on there being a column titled "name" in all lower case.
