### ISSUE TITLE
Excel: implement Units Object

### ISSUE THREAD

**Issue by valentinedwv** [CZOData/YODA-File#32]
Presently a string

**Comment by SRGDamia1** [comment]
This has been implemented in 0.3.2.  We still need to discuss how it the units can be improved, though.  Ideally, we'd have a way of matching up the units with our "stock" of units (http://vocabulary.odm2.org/units/) so users will always have things matched up and there won't be any repeats of things like "mL" and "Milliliter" and "milliliter" and "millilitre"

**Comment by horsburgh** [comment]
Agreed - the list of units is now live on the CV system at vocabulary.odm2.org.  So, we could modify the code that updates the CVs to also load the list of units.
