### ISSUE TITLE
"AffiliationStartDate" column in "Affiliations" table

### ISSUE THREAD

**Issue by cdesyoun** [CZOData/YODA-File#39]
Jeff, the data type for "AffiliationStartDate" and "AffiliationEndDate" is "Date" type, not "Datetime" type.
In generated timeseries yoda file, 

```
,AffiliationStartDate: "2014-01-01 00:00:00", 
,AffiliationStartDate: "2015-01-01 00:00:00",
```

When validating it, the error was occurred.
The correction is as follows:

```
,AffiliationStartDate: "2014-01-01", 
,AffiliationStartDate: "2015-01-01",
```

**Comment by horsburgh** [comment]
@cdesyoun - I'll have to look into this one and see if I can get Excel to spit out just the date string without the time.

**Comment by horsburgh** [comment]
This should be fixed in the new Time Series Excel template and in the example.  @cdesyoun - can you have a look and close this issue if you are satisfied?

**Comment by cdesyoun** [comment]
It is awesome! when testing this updated YODA file, the validating process was successful.
Thanks for the quick update, Jeff.
