### ISSUE TITLE
Additional info in yoda header?

### ISSUE THREAD

**Issue by valentinedwv** [CZOData/YODA-File#4]
## Present

YODA:
## propose

YODA:
- {Version: 1.0.0, Profile: TimeSeries, dataCreated: 2015-01-01, datafileUpdated: 2015-03-17 , contact:
  *ReferenceToPerson }

**Comment by horsburgh** [comment]
Good ideas. If we want to use a reference to a person in this block (the contact person), the reference couldn't come before the definition of the anchor for the person (YAML parsers don't allow this). I think it would be good to keep the YODA block as the very first block in every YODA file. Should we just expand the contact person details in the YODA block?  This would be the contact information for the person responsible for the YODA file and not necessarily the people associated with the data.

**Comment by SRGDamia1** [comment]
What exactly would the "dataCreated" and "datafileUpdated" fields be for?

**Comment by valentinedwv** [comment]
These are stored on disk. 
So when this file was first created.
And when it was last updated

**Comment by SRGDamia1** [comment]
If it's for the date when the datafile was created then we should say "datafileCreated" not "dataCreated."

**Comment by horsburgh** [comment]
Or just dateCreated and dateUpdated.

**Comment by SRGDamia1** [comment]
Do we also want to include information about the tool used to produce the YAML?

**Comment by valentinedwv** [comment]
That sounds like a good idea.
Tool: name, version

**Comment by emiliom** [comment]
> Do we also want to include information about the tool used to produce the YAML?

That can often be very useful information. You might want to think about where that information would go when loading into an ODM2 database instance. Could be simply text that's part of Actions.ActionDescription in a YODA data-loading action. Or Methods.MethodDescription, if data loading from a YODA file has been discussed as being a specific "method".

**Comment by SRGDamia1** [comment]
So this is the current header I'm putting in the excel template:

YODA: {YODAVersion: “1.0.0”, Profile: “TimeSeries”, CreationTool: “Excel Template v1.0”, DateCreated: "2015-03-13", DateUpdated: "2015-03-13"}

**Comment by horsburgh** [comment]
For consistency with the other blocks, do it this way:

YODA: 
  - {YODAVersion: “1.0.0”, Profile: “TimeSeries”, CreationTool: “Excel Template v1.0”, DateCreated: "2015-03-13", DateUpdated: "2015-03-13"}

Are we enclosing everything in quotation marks?

**Comment by SRGDamia1** [comment]
Changed.

And I have been putting quotes around all text and date fields even though it's not strictly necessary.  The online parser I was testing against kept failing, especially with dates, so I decided it was safer to just put them in everywhere.

**Comment by horsburgh** [comment]
I put this additional information in the YODA block of the iUTAH examples.  I think the "YODAVersion" element should just be "Version".  It's within the YODA block, so "YODAVersion" is redundant.

I'm going to create a separate issue about how much of the text in the YODA files we want to enclose in quotations.
