### ISSUE TITLE
loading YODA file into postgresql db

### ISSUE THREAD

**Issue by cdesyoun** [CZOData/YODA-File#40]
Jeff, when loading YODA file into postgresql db, there are lots of foreign key integration errors related to CV which is used for most of odm2 tables. unlike sqlite and mySQL, without disabling this constraint forcibly for each tables in postgresql, YODA data could not be loaded into it.
For this, probably, using odm2 CV services, I think related CV terms will be loaded into the database in advance. Or any other way to do this?

**Comment by emiliom** [comment]
@cdesyoun, yes, you do need to pre-load the CV's.

Use [cvload.py](https://github.com/ODM2/ODM2/tree/master/src/load_cvs). It's straightforward.

**Comment by cdesyoun** [comment]
Thanks! Emilio. I will test it.

**Comment by cdesyoun** [comment]
Yes, when testing and looking into this file, it was good.
