### ISSUE TITLE
Time Series Template: dropdown for VariableCode in Data Columns tab

### ISSUE THREAD

**Issue by AmberSJones** [CZOData/YODA-File#43]
On the "Data Columns" tab, the fields that refer to other tabs Include a drop down menu for selection- e.g., Method Code, Units, etc. The template needs a drop down menu for the "Variable Code" column that references the "Variables" tab.  Also need to highlight the variable code cells red if a code is entered that is not listed within the "Variables" tab.
![image 3](https://cloud.githubusercontent.com/assets/5023186/12625181/dbf122c4-c4ef-11e5-83fa-9c5d252997ae.png)

**Comment by SRGDamia1** [comment]
@AmberSJones, I'm a bit puzzled by what you mean in this issue.  Even the versions that I'd originally posted a year ago had a variable code column with a drop-down and 0.3.2 definitely does.  The error formatting also seems to be working fine to me in 0.3.2, even if it wasn't in earlier versions.  I'm closing this issue.
