### ISSUE TITLE
Author Lists and DatasetCitations missing in iUtah examples

### ISSUE THREAD

**Issue by SRGDamia1** [CZOData/YODA-File#5]
In all of the iUtah examples the "AuthorList" block is missing the required "CitationID" field.  (This should be a link to a *CitationID###.)  There also isn't a "DatasetCitations" block to link the dataset and the citation and corresponding to the table of the same name.

**Comment by horsburgh** [comment]
We fixed the first one yesterday and I asked Jacob to commit his changes.  I will remind him to do so.

The DataSetCitations is something we might want to discuss.  This is an exchange format, so the question is - do data managers assign a citation to the dataset, or does it get assigned by say the CZOData Central system after the file has been received and processed?

**Comment by SRGDamia1** [comment]
Hm.  I'm setting up the excel template assuming the former.

**Comment by horsburgh** [comment]
I just added the DataSetCitations block to the iUTAH examples.  This required me to add anchors to the Dataset and the Citation so I could reference them in DataSetCitations.  This change makes the YODA files more consistent with the ODM2 schema.

I think this will work out - If a data manager wants to send a citation with the dataset in the YAML file, it will be encoded as it is in the iUTAH examples.  A CZO Central citation could also be added - ODM allows for multiple citations for a single dataset, and the two can be related.

**Comment by horsburgh** [comment]
This has been addressed.
