### ISSUE TITLE
generating YODA file from timeseries excel files

### ISSUE THREAD

**Issue by cdesyoun** [CZOData/YODA-File#53]
@AmberSJones I have implemented yoda tool to read data in excel template and generate yoda file.
There are examples in this link, https://github.com/ODM2/YODA-Tools/tree/master/src/yoda_tools/examples/generatedYODAfiles. When looking into these files, there are two excel templates (https://github.com/ODM2/YODA-File/blob/master/examples/time_series/YODA_v0.3.2_TS_multiple_LR_GC_C.xlsm, https://github.com/ODM2/YODA-File/blob/master/examples/time_series/YODA_v0.3.2_TS_multiple_LR_Mendon_AA.xlsm) that do not match the rules between "Data Columns" sheet and "Data Values" sheet. The number of columns between two sheets is different and "Data Values" sheet should contain column names in the first row.
From these YODA files, I see lots of "None" values because data values in this sheet are not specified aligning columns in "Data Columns" sheet.

**Comment by AmberSJones** [comment]
Thanks for pointing this out, @cdesyoun . Simultaneously, @PhilSuiter noticed that there was not a header row in the 'Data Values' sheet, which he added to new versions of the files. The column names are consistent between the 'Data Columns' and 'Data Values' sheets, and the counts are the same (other than the DateTime and UTCOffset columns). I will get those files loaded shortly.

**Comment by AmberSJones** [comment]
@cdesyoun - we have added new files to the time series example folder that include the header rows. The column names seem to be fine. Let me know if you notice any other issues.

https://github.com/ODM2/YODA-File/blob/master/examples/time_series/YODA_v0.3.2_TS_multiple_LR_GC_C_headers.xlsm
https://github.com/ODM2/YODA-File/blob/master/examples/time_series/YODA_v0.3.2_TS_multiple_LR_Mendon_AA_headers.xlsm

**Comment by cdesyoun** [comment]
@AmberSJones Thank you so much for adding those files. It is so cool! I think I was able to generate timeseries YODA files from these correct timeseries excel files. Based on that, I fixed some bugs and pushed these generated YODA files into github.
